//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFLWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteAnagrafica_CLS2F
    {
        public string CDCLI { get; set; }
        public string RASCL { get; set; }
        public string RASC2 { get; set; }
        public string CDRIC { get; set; }
        public string INDCL { get; set; }
        public string LOCCL { get; set; }
        public string PROCL { get; set; }
        public string CAPCL { get; set; }
        public string NTECL { get; set; }
        public string CNOTE { get; set; }
        public string CDFIS { get; set; }
        public string CPAIV { get; set; }
        public string COPAG { get; set; }
        public string PROVG { get; set; }
        public string CDAGE { get; set; }
        public string CDCPZ { get; set; }
        public string CDLIS { get; set; }
        public string FIDOCE { get; set; }
        public string CVAS1 { get; set; }
        public string CVAS2 { get; set; }
        public string CSCCA { get; set; }
        public string CCAVE { get; set; }
        public string CROOB { get; set; }
        public string CLSCO { get; set; }
        public string CTRAS { get; set; }
        public string ACCMS { get; set; }
        public string CFLG4 { get; set; }
        public string CDMCL { get; set; }
        public string CBAAP { get; set; }
        public string CAGAP { get; set; }
        public string DSAGE { get; set; }
        public string MODCO { get; set; }
        public string CPORT { get; set; }
        public string MODSP { get; set; }
        public string CATVE { get; set; }
        public string FAXCL { get; set; }
        public string CNFAX { get; set; }
        public string CNTLX { get; set; }
        public string CZONA { get; set; }
        public string INECL { get; set; }
        public string GRUCO { get; set; }
        public string XXXXX { get; set; }
    }
}
