//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFLWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comuni
    {
        public int Id { get; set; }
        public int CodiceRegione { get; set; }
        public string DenominazioneRegione { get; set; }
        public string SiglaProvincia { get; set; }
        public string DenominazioneProvincia { get; set; }
        public string DenominazioneComune { get; set; }
        public string CodiceCatastaleComune { get; set; }
        public int CodiceRipartizioneGeografica { get; set; }
        public string RipartizioneGeografica { get; set; }
    }
}
