//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFLWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ResidenceCity { get; set; }
        public string ResidenceCountry { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public bool Newsletter { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public System.DateTime LastLoginDateUtc { get; set; }
        public string BusinessName { get; set; }
        public string CityOfBirth { get; set; }
        public bool CommercialNewsletter { get; set; }
        public bool CommercialNewsletterOtherCompany { get; set; }
        public string CountryOfBirth { get; set; }
        public string CustomerCode { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public System.DateTime LastModifiedOnUtc { get; set; }
        public bool MarketAnalysisNewsletter { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string ResidenceAddress { get; set; }
        public string ResidenceAddressNumber { get; set; }
        public string ResidenceCAP { get; set; }
        public string FiscalCode { get; set; }
        public string Token { get; set; }
        public string ResetToken { get; set; }
        public byte[] ResetTokenSalt { get; set; }
    }
}
