//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFLWebForm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataEntities : DbContext
    {
        public DataEntities()
            : base("name=DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comuni> Comuni { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<PromoApp> PromoApp { get; set; }
        public virtual DbSet<Articoli_ARS2F> Articoli_ARS2F { get; set; }
        public virtual DbSet<DFL_GruppoSottogruppo_GSS2F> DFL_GruppoSottogruppo_GSS2F { get; set; }
        public virtual DbSet<Mails> Mails { get; set; }
        public virtual DbSet<MailsType> MailsType { get; set; }
        public virtual DbSet<Promozioni_PRS2F> Promozioni_PRS2F { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductProperty> ProductProperty { get; set; }
        public virtual DbSet<Promo> Promo { get; set; }
        public virtual DbSet<View_App_Pubb_Articoli> View_App_Pubb_Articoli { get; set; }
        public virtual DbSet<View_App_Pubb_Clienti> View_App_Pubb_Clienti { get; set; }
        public virtual DbSet<View_App_Pubb_Gruppo_Sottogruppo> View_App_Pubb_Gruppo_Sottogruppo { get; set; }
        public virtual DbSet<View_App_Pubb_Promo_Omaggi> View_App_Pubb_Promo_Omaggi { get; set; }
        public virtual DbSet<View_App_Pubb_Promo_Omaggi_05> View_App_Pubb_Promo_Omaggi_05 { get; set; }
        public virtual DbSet<View_App_Pubb_Promozioni> View_App_Pubb_Promozioni { get; set; }
        public virtual DbSet<View_App_Pubb_Promozioni_Clienti_05> View_App_Pubb_Promozioni_Clienti_05 { get; set; }
        public virtual DbSet<View_App_Pubb_Tabelle_Promozioni> View_App_Pubb_Tabelle_Promozioni { get; set; }
        public virtual DbSet<ProdottiApp> ProdottiApp { get; set; }
        public virtual DbSet<AdminApp> AdminApp { get; set; }
        public virtual DbSet<Vetrina> Vetrina { get; set; }
    
        public virtual int ActivateAllPromoProduct(string promoid)
        {
            var promoidParameter = promoid != null ?
                new ObjectParameter("promoid", promoid) :
                new ObjectParameter("promoid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ActivateAllPromoProduct", promoidParameter);
        }
    
        public virtual ObjectResult<GetProductProperty_Result> GetProductProperty(string idproduct)
        {
            var idproductParameter = idproduct != null ?
                new ObjectParameter("idproduct", idproduct) :
                new ObjectParameter("idproduct", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProductProperty_Result>("GetProductProperty", idproductParameter);
        }
    }
}
