//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFLWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string CDART { get; set; }
        public string DEART { get; set; }
        public string CDMAR { get; set; }
        public string CDCAT { get; set; }
        public Nullable<decimal> NCARB { get; set; }
        public string DDESS { get; set; }
        public string FRETIT { get; set; }
        public string FREDES { get; set; }
        public string NMDIS { get; set; }
        public Nullable<System.DateTime> DTCRA { get; set; }
        public string DescrizioneGruppoMerceologico { get; set; }
        public string DescrizioneSottoGruppoMerceologico { get; set; }
        public string DescrizionePromo { get; set; }
        public string PercorsoImmagine { get; set; }
        public int PromoAppId { get; set; }
        public string PZRPRP { get; set; }
        public Nullable<System.DateTime> PZTDI { get; set; }
        public Nullable<System.DateTime> PZTDF { get; set; }
        public string PZTDE { get; set; }
        public string CodiceProdottoApp { get; set; }
        public string CodicePromo { get; set; }
        public string PZTID { get; set; }
        public string Vetrina { get; set; }
    }
}
