//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFLWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProperty
    {
        public string CDART { get; set; }
        public string FRET01 { get; set; }
        public string FRET02 { get; set; }
        public string FRET03 { get; set; }
        public string FRET04 { get; set; }
        public string FRET05 { get; set; }
        public string FRET06 { get; set; }
        public string FRET07 { get; set; }
        public string FRET08 { get; set; }
        public string FRET09 { get; set; }
        public string FRET10 { get; set; }
        public string FRET11 { get; set; }
        public string FRET12 { get; set; }
        public string FRET13 { get; set; }
        public string FRET14 { get; set; }
        public string FRET15 { get; set; }
        public string FRET16 { get; set; }
        public string FRET17 { get; set; }
        public string FRET18 { get; set; }
        public string FRET19 { get; set; }
        public string FRET20 { get; set; }
        public string FRET21 { get; set; }
        public string FRET22 { get; set; }
        public string FRET23 { get; set; }
        public string FRET24 { get; set; }
        public string FRET25 { get; set; }
        public string FRET26 { get; set; }
        public string FRET27 { get; set; }
        public string FRET28 { get; set; }
        public string FRET29 { get; set; }
        public string FRET30 { get; set; }
        public string FRET31 { get; set; }
        public string FRET32 { get; set; }
        public string FRET33 { get; set; }
        public string FRET34 { get; set; }
        public string FRET35 { get; set; }
        public string FRET36 { get; set; }
        public string FRET37 { get; set; }
        public string FRET38 { get; set; }
        public string FRET39 { get; set; }
        public string FRET40 { get; set; }
        public string FRET41 { get; set; }
        public string FRET42 { get; set; }
        public string FRET43 { get; set; }
        public string FRET44 { get; set; }
        public string FRET45 { get; set; }
        public string FRET46 { get; set; }
        public string FRET47 { get; set; }
        public string FRET48 { get; set; }
        public string FRET49 { get; set; }
        public string FRET50 { get; set; }
        public string FRET51 { get; set; }
        public string FRET52 { get; set; }
        public string FRET53 { get; set; }
        public string FRET54 { get; set; }
        public string FRET55 { get; set; }
        public string FRET56 { get; set; }
        public string FRET57 { get; set; }
        public string FRET58 { get; set; }
        public string FRET59 { get; set; }
        public string FRET60 { get; set; }
        public string FRET61 { get; set; }
        public string FRET62 { get; set; }
        public string FRET63 { get; set; }
        public string FRET64 { get; set; }
        public string FRET65 { get; set; }
        public string FRET66 { get; set; }
        public string FRET67 { get; set; }
        public string FRET68 { get; set; }
        public string FRET69 { get; set; }
        public string FRET70 { get; set; }
        public string FREV01 { get; set; }
        public string FREV02 { get; set; }
        public string FREV03 { get; set; }
        public string FREV04 { get; set; }
        public string FREV05 { get; set; }
        public string FREV06 { get; set; }
        public string FREV07 { get; set; }
        public string FREV08 { get; set; }
        public string FREV09 { get; set; }
        public string FREV10 { get; set; }
        public string FREV11 { get; set; }
        public string FREV12 { get; set; }
        public string FREV13 { get; set; }
        public string FREV14 { get; set; }
        public string FREV15 { get; set; }
        public string FREV16 { get; set; }
        public string FREV17 { get; set; }
        public string FREV18 { get; set; }
        public string FREV19 { get; set; }
        public string FREV20 { get; set; }
        public string FREV21 { get; set; }
        public string FREV22 { get; set; }
        public string FREV23 { get; set; }
        public string FREV24 { get; set; }
        public string FREV25 { get; set; }
        public string FREV26 { get; set; }
        public string FREV27 { get; set; }
        public string FREV28 { get; set; }
        public string FREV29 { get; set; }
        public string FREV30 { get; set; }
        public string FREV31 { get; set; }
        public string FREV32 { get; set; }
        public string FREV33 { get; set; }
        public string FREV34 { get; set; }
        public string FREV35 { get; set; }
        public string FREV36 { get; set; }
        public string FREV37 { get; set; }
        public string FREV38 { get; set; }
        public string FREV39 { get; set; }
        public string FREV40 { get; set; }
        public string FREV41 { get; set; }
        public string FREV42 { get; set; }
        public string FREV43 { get; set; }
        public string FREV44 { get; set; }
        public string FREV45 { get; set; }
        public string FREV46 { get; set; }
        public string FREV47 { get; set; }
        public string FREV48 { get; set; }
        public string FREV49 { get; set; }
        public string FREV50 { get; set; }
        public string FREV51 { get; set; }
        public string FREV52 { get; set; }
        public string FREV53 { get; set; }
        public string FREV54 { get; set; }
        public string FREV55 { get; set; }
        public string FREV56 { get; set; }
        public string FREV57 { get; set; }
        public string FREV58 { get; set; }
        public string FREV59 { get; set; }
        public string FREV60 { get; set; }
        public string FREV61 { get; set; }
        public string FREV62 { get; set; }
        public string FREV63 { get; set; }
        public string FREV64 { get; set; }
        public string FREV65 { get; set; }
        public string FREV66 { get; set; }
        public string FREV67 { get; set; }
        public string FREV68 { get; set; }
        public string FREV69 { get; set; }
        public string FREV70 { get; set; }
    }
}
