//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFLWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promozioni_PRS2F
    {
        public string PZTCD { get; set; }
        public string PZTDE { get; set; }
        public string PZTD1 { get; set; }
        public string PZTD2 { get; set; }
        public string PZTD3 { get; set; }
        public Nullable<System.DateTime> PZTDI { get; set; }
        public Nullable<System.DateTime> PZTDF { get; set; }
        public string PZTID { get; set; }
        public string PZTCV { get; set; }
        public string PZTCC { get; set; }
        public string PZTTC { get; set; }
        public string PZTTA { get; set; }
        public string PZRID { get; set; }
        public string PZRAR { get; set; }
        public string PZRQL { get; set; }
        public string PZRPA { get; set; }
        public string PZRLI { get; set; }
        public Nullable<decimal> PZRPZ { get; set; }
        public Nullable<decimal> PZRS1 { get; set; }
        public Nullable<decimal> PZRS2 { get; set; }
        public Nullable<decimal> PZRS3 { get; set; }
        public Nullable<decimal> PZRS4 { get; set; }
        public Nullable<decimal> PZRS5 { get; set; }
        public Nullable<decimal> PZRBO { get; set; }
        public Nullable<decimal> PZRP1 { get; set; }
        public Nullable<decimal> PZRP2 { get; set; }
        public string PZRFQ { get; set; }
        public Nullable<decimal> PZRQO { get; set; }
        public Nullable<decimal> PZRQP { get; set; }
        public string PZRTO { get; set; }
        public string PZRAS { get; set; }
        public string PZRFP { get; set; }
        public string PZRTP { get; set; }
        public Nullable<decimal> PZRE1 { get; set; }
        public Nullable<decimal> PZRE2 { get; set; }
        public Nullable<decimal> PZRE3 { get; set; }
        public Nullable<decimal> PZRE4 { get; set; }
        public Nullable<decimal> PZRE5 { get; set; }
        public Nullable<decimal> PZRSU { get; set; }
        public Nullable<decimal> PZRU1 { get; set; }
        public Nullable<decimal> PZRU2 { get; set; }
        public string PZRPRP { get; set; }
        public string PZRRIC { get; set; }
        public string XXXXX { get; set; }
    }
}
