//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFLWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromoApp
    {
        public int Id { get; set; }
        public string CodicePromo { get; set; }
        public string DescrizionePromo { get; set; }
        public string SottotitoloPromo { get; set; }
        public string TestoPromo { get; set; }
        public string PercorsoImmagine { get; set; }
        public string PercorsoLogo { get; set; }
        public Nullable<bool> Attiva { get; set; }
    }
}
