//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFLWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_App_Pubb_Promo_Omaggi
    {
        public string PZOID { get; set; }
        public string PZOIR { get; set; }
        public string PZOPY { get; set; }
        public string PZOAR { get; set; }
        public string PZOFQ { get; set; }
        public string PZOQO { get; set; }
        public string PZOQP { get; set; }
        public string PZOTO { get; set; }
        public string PZOLI { get; set; }
        public string PZOPZ { get; set; }
        public string XXXXX { get; set; }
    }
}
