//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFLWebForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_App_Pubb_Gruppo_Sottogruppo
    {
        public string TIPGS { get; set; }
        public string CODGS { get; set; }
        public string DESGS { get; set; }
        public string XXXXX { get; set; }
    }
}
